# Generated by Django 4.0.5 on 2022-06-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0007_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
